package VENTANAS;

import ENTIDADES.Blusa;
import ENTIDADES.Camisa;
import ENTIDADES.Falda;
import ENTIDADES.Pantalon;
import java.util.ArrayList;
import java.util.List;

public class PRINCIPAL extends javax.swing.JFrame {

    public List<Camisa> listacamisas= new ArrayList<>(); 
    public List<Pantalon> listapantalones= new ArrayList<>(); 
    public List<Falda> listafaldas= new ArrayList<>(); 
    public List<Blusa> listablusas= new ArrayList<>(); 

    public PRINCIPAL() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaRopa = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Doble click para ver los precios");

        listaRopa.setBorder(null);
        listaRopa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        listaRopa.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Camisas", "Pantalones", "Faldas", "Blusas" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaRopa.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaRopa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaRopaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaRopa);

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LISTA DE PRECIOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaRopaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaRopaMouseClicked
        //Mandamos a la lista correspondiente
        if (evt.getClickCount() == 2 && listaRopa.getSelectedIndex() != -1){
            //Vamos a buscar el string en la lista actual de Estudiante
            V_PRECIOS ventana;
            int  index = listaRopa.getSelectedIndex();
            
            switch (index) {
                case 0:
                    ventana = new V_PRECIOS(this,1);
                    ventana.ActualizarModelo();
                    this.dispose();
                    break;
                case 1:
                    ventana = new V_PRECIOS(this,2);
                    ventana.ActualizarModelo();
                    this.dispose();
                    break;
                case 2:
                    ventana = new V_PRECIOS(this,3);
                    ventana.ActualizarModelo();
                    this.dispose();
                    break;
                case 3:
                    ventana = new V_PRECIOS(this,4);
                    ventana.ActualizarModelo();
                    this.dispose();
                    break;
                default:
                    throw new AssertionError();
            }
        }
    }//GEN-LAST:event_listaRopaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaRopa;
    // End of variables declaration//GEN-END:variables
}
